title = "Shared Prayers"
baseURL = "http://www.sharedprayers.net"
languageCode = "en-us"
theme = "zen"
publishDir = "docs"
pluralizelisttitles = false
buildfuture = true
sectionPagesMenu = 'main'

# Disable rss to eliminate oversized index.xml (56M) per github complaint
disableKinds = ['rss']

[markup.goldmark.renderer]
hardWraps = true

[params]
copyright = "CC-SA-4.0"
favicon = "apple-touch-icon.png"
realfavicongenerator = true
jquery = false
mainSections = ""

